spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "clientid"
            client-secret: "clientsecret"
            scope:
              - profile
              - email
          naver:
            client-id: "clientid"
            client-secret: "clientsecret"
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization_grant_type: authorization_code
            scope:
              - name
              - email
              - profile_image
            client-name: naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

